# Generated by Django 5.2.4 on 2025-07-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('course', models.CharField(max_length=100)),
                ('message', models.TextField(blank=True)),
                ('state', models.CharField(default='Maharashtra', max_length=100)),
                ('district', models.CharField(default='Kolhapur', max_length=100)),
                ('subdistrict', models.CharField(default='Hatkanangale', max_length=100)),
                ('city', models.CharField(default='Kolhapur', max_length=100)),
                ('pincode', models.CharField(default='416003', max_length=6)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
