# Generated by Django 5.2.4 on 2025-07-22 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='course_name',
            new_name='name',
        ),
    ]
