# Generated by Django 5.2.4 on 2025-07-22 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_syllabus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='syllabus',
            name='description',
        ),
        migrations.RemoveField(
            model_name='syllabus',
            name='title',
        ),
        migrations.AddField(
            model_name='syllabus',
            name='syllabus_pdf',
            field=models.FileField(default='syllabus_pdfs/sample.pdf', upload_to='syllabus_pdfs/'),
            preserve_default=False,
        ),
    ]
