# Generated by Django 5.2.4 on 2025-07-22 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_aboutus'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalientFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('fa-star', 'Star'), ('fa-lightbulb', 'Lightbulb'), ('fa-cogs', 'Cogs'), ('fa-rocket', 'Rocket'), ('fa-book', 'Book')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='about_us_images/'),
        ),
    ]
