# Generated by Django 5.2.4 on 2025-07-22 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_salientfeature_alter_aboutus_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salientfeature',
            name='icon',
            field=models.CharField(choices=[('fas fa-users', 'Only 25 students batch'), ('fas fa-book-open', 'Basic fundamentals of English'), ('fas fa-desktop', 'Digital Computerized Lab'), ('fas fa-chalkboard-teacher', 'Digital Interactive Classroom'), ('fas fa-book', 'Well-equipped Library'), ('fas fa-file-alt', 'Well-designed study material'), ('fas fa-female', 'Separate batch for women learners'), ('fas fa-user-friends', 'Age groupwise batches'), ('fas fa-user-tie', 'Experienced and Expert Faculties')], max_length=50),
        ),
        migrations.AlterField(
            model_name='salientfeature',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
