# Generated by Django 5.2.4 on 2025-07-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_salientfeature_icon_alter_salientfeature_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='gallery_images/')),
            ],
        ),
        migrations.DeleteModel(
            name='SalientFeature',
        ),
    ]
