# Generated by Django 5.2.4 on 2025-07-22 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_academyfeature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academyfeature',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
