# Generated by Django 5.2.4 on 2025-07-23 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.admission'),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.course'),
        ),
    ]
