# Generated by Django 5.2.4 on 2025-07-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_student_course_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_photo',
            field=models.ImageField(blank=True, null=True, upload_to='course_photos/'),
        ),
    ]
