# Generated by Django 3.2 on 2025-07-31 07:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_student_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='phone',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be 10 digits and start with 6, 7, 8, or 9.', regex='^[6-9]\\d{9}$')]),
        ),
        migrations.AlterField(
            model_name='admission',
            name='pincode',
            field=models.CharField(default='416003', max_length=6, validators=[django.core.validators.RegexValidator(message='Pincode must be exactly 6 digits.', regex='^\\d{6}$')]),
        ),
    ]
