# Generated by Django 3.2 on 2025-07-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20250731_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='phone',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='admission',
            name='pincode',
            field=models.CharField(default='416003', max_length=6),
        ),
    ]
